import { CONFIG } from './config.js';
import { beginDeviceFlow, checkSession, clearPendingDeviceFlow, fetchPostsInitial, fetchRemainingPosts, getCachedPostsSnapshot, getCachedUser, getPendingDeviceFlow, isLoggedIn, issueRoute, repoUrl, setCachedUser, pollDeviceFlow, signOut } from './github.js';
import { applyLanguage, initI18n, tr, getLanguage } from './i18n.js';
const $ = (selector, scope = document) => scope.querySelector(selector);
const $$ = (selector, scope = document) => [...scope.querySelectorAll(selector)];
const PAGE_SIZE = 5;
const state = { posts: [], filteredPosts: [], sort: 'updated', query: '', expanded: false, serverComplete: false, nextPage: null, loading: false, loadingAll: false, feedStatus: 'loading', user: null, oauthAbort: null };
function safeText(value = '') { return String(value).replace(/[&<>'"]/g, ch => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#039;', '"': '&quot;' }[ch])); }
function safeUrl(value = '') { try { const url = new URL(value, location.href); return ['http:', 'https:'].includes(url.protocol) ? url.href : ''; } catch { return ''; } }
function formatDate(value) { const date = new Date(value); if (Number.isNaN(date.getTime())) return '—'; return new Intl.DateTimeFormat(tr('locale'), { month: 'short', day: 'numeric', year: 'numeric' }).format(date); }
function initTheme() { let theme = ''; try { theme = localStorage.getItem(CONFIG.storage.theme) || localStorage.getItem(CONFIG.storage.legacyTheme) || ''; } catch {} setTheme(theme || 'light', false); }
function setTheme(theme, persist = true) { const value = theme === 'dark' ? 'dark' : 'light'; document.documentElement.dataset.theme = value; document.documentElement.style.colorScheme = value; document.querySelector('meta[name="theme-color"]')?.setAttribute('content', value === 'dark' ? '#0b0d0f' : '#f3f4f5'); if (persist) { try { localStorage.setItem(CONFIG.storage.theme, value); } catch {} } }
function toggleTheme() { setTheme(document.documentElement.dataset.theme === 'dark' ? 'light' : 'dark'); }
function updateHeader() { $('#topbar')?.classList.toggle('is-scrolled', window.scrollY > 16); }
function setAuthButton() { const button = $('#authTopButton'); if (!button) return; const logged = Boolean(state.user); button.classList.toggle('is-connected', logged); button.setAttribute('aria-pressed', String(logged)); const label = button.querySelector('[data-auth-label]'); if (label) label.textContent = logged ? `${tr('connectedAs')} ${state.user.login}` : tr('navConnect'); }
function showAuthToast(message = tr('loginRequired'), duration = 2600) { const toast = $('#authToast'); if (!toast) return; const label = toast.querySelector('[data-auth-message]') || toast.querySelector('[data-i18n]'); if (label) label.textContent = message; toast.hidden = false; clearTimeout(showAuthToast.timer); showAuthToast.timer = setTimeout(() => { toast.hidden = true; }, duration); }
function setButtonBusy(button, busy, labelKey = 'loginStart') { if (!button) return; button.disabled = busy; button.setAttribute('aria-busy', String(busy)); const label = button.querySelector('span:first-child'); if (!label) return; if (busy) { if (!button.dataset.idleLabel) button.dataset.idleLabel = label.textContent; label.textContent = tr(labelKey); } else { label.textContent = button.dataset.idleLabel || label.textContent; delete button.dataset.idleLabel; } }
async function restoreUser() { if (!isLoggedIn()) { state.user = null; setAuthButton(); return; } const cached = getCachedUser(); if (cached) { state.user = cached; setAuthButton(); } try { const session = await checkSession(); if (session.ok) { state.user = session.user; setCachedUser(session.user); } else state.user = null; } catch { if (!cached || !isLoggedIn()) state.user = null; } setAuthButton(); }
function getPendingFlow() { return getPendingDeviceFlow(); }
function openConnect() { const dialog = $('#connectDialog'); if (!dialog) return; const pending = getPendingFlow(); const start = $('#oauthStartView'); const pendingView = $('#oauthPendingView'); if (pending) { start.hidden = true; pendingView.hidden = false; setLoginPendingUI(pending); } else { start.hidden = false; pendingView.hidden = true; $('#oauthStatus').textContent = tr('loginWaiting'); $('#oauthStartStatus').textContent = ''; $('#oauthCode').textContent = '---- ----'; $('#oauthCode').removeAttribute('data-code'); $('#oauthCountdown').textContent = ''; $('#verificationLink').href = CONFIG.github.oauth.verificationUrl; } if (typeof dialog.showModal === 'function') { if (!dialog.open) dialog.showModal(); } else dialog.setAttribute('open', ''); }
function closeConnect() { const dialog = $('#connectDialog'); if (typeof dialog?.close === 'function') dialog.close(); else dialog?.removeAttribute('open'); clearInterval(setLoginPendingUI.timer); }
function cancelGithubLogin() { if (state.oauthAbort) { state.oauthAbort.abort(); state.oauthAbort = null; } clearPendingDeviceFlow(); $('#oauthStartView').hidden = false; $('#oauthPendingView').hidden = true; $('#oauthStartStatus').textContent = ''; $('#oauthStatus').textContent = tr('loginCancelled'); $('#oauthCode').textContent = '---- ----'; $('#oauthCode').removeAttribute('data-code'); $('#oauthCountdown').textContent = ''; closeConnect(); }
function setLoginPendingUI(flow) { const expiresAt = Number(flow.expiresAt || Date.now() + Number(flow.expiresIn || 900) * 1000); $('#oauthStartView').hidden = true; $('#oauthPendingView').hidden = false; $('#oauthCode').textContent = flow.userCode || '---- ----'; $('#oauthCode').dataset.code = flow.userCode || ''; $('#verificationLink').href = flow.verificationUri || CONFIG.github.oauth.verificationUrl; $('#oauthStatus').textContent = tr('loginPending'); const countdown = $('#oauthCountdown'); clearInterval(setLoginPendingUI.timer); const tick = () => { const left = Math.max(0, Math.ceil((expiresAt - Date.now()) / 1000)); if (countdown) countdown.textContent = left ? `${Math.floor(left / 60)}:${String(left % 60).padStart(2, '0')}` : '0:00'; if (!left) clearInterval(setLoginPendingUI.timer); }; tick(); setLoginPendingUI.timer = setInterval(tick, 1000); }
function openVerificationTab() { try { const popup = window.open('', 'nullspire-github-login'); if (popup) { try { popup.opener = null; } catch {} return popup; } } catch {} return null; }
async function runGithubLogin(flow, controller, popup = null) { setLoginPendingUI(flow); if (popup) popup.location.href = flow.verificationUri || CONFIG.github.oauth.verificationUrl; const user = await pollDeviceFlow(flow, { signal: controller.signal, onPending: () => { $('#oauthStatus').textContent = tr('loginPending'); }, onSlowDown: interval => { $('#oauthStatus').textContent = `${tr('loginSlow')} ${interval}s`; }, onSuccess: () => { $('#oauthStatus').textContent = tr('loginSuccess'); } }); const session = await checkSession(); if (!session.ok) throw new Error(tr('loginVerificationFailed')); state.user = session.user || user; setCachedUser(state.user); setAuthButton(); closeConnect(); showAuthToast(`${tr('loginSuccess')} ${state.user.login}`, 2400); }
async function startGithubLogin({ autoOpen = true } = {}) { if (state.oauthAbort) { openConnect(); return; } if (!CONFIG.github.oauth.clientId) { $('#oauthStatus').textContent = tr('oauthClientMissing'); return; } const controller = new AbortController(); let popup = null; state.oauthAbort = controller; const button = $('#startGithubLogin'); try { if (autoOpen) popup = openVerificationTab(); setButtonBusy(button, true, 'loginPleaseWait'); $('#oauthStartStatus').textContent = tr('loginPleaseWait'); $('#oauthStatus').textContent = tr('loginPleaseWait'); const pending = getPendingFlow(); const flow = pending || await beginDeviceFlow(); setLoginPendingUI(flow); await runGithubLogin(flow, controller, popup); } catch (error) { if (popup && !popup.closed) { try { popup.close(); } catch {} } if (error?.name === 'AbortError') { $('#oauthStatus').textContent = tr('loginCancelled'); $('#oauthStartStatus').textContent = tr('loginCancelled'); } else { const message = error.message || tr('loginCancelled'); $('#oauthStatus').textContent = message; $('#oauthStartStatus').textContent = message; } } finally { state.oauthAbort = null; setButtonBusy(button, false, 'loginStart'); clearInterval(setLoginPendingUI.timer); if (!state.user && !getPendingFlow()) { $('#oauthStartView').hidden = false; $('#oauthPendingView').hidden = true; } } }
async function resumePendingLogin() { if (state.user || state.oauthAbort) return; const flow = getPendingFlow(); if (!flow) return; openConnect(); await startGithubLogin({ autoOpen: false }); }
async function checkLogin() { const button = $('#checkLoginButton'); if (!button || button.disabled) return; setButtonBusy(button, true, 'checkingLogin'); try { const session = await checkSession(); if (session.ok) { state.user = session.user; setCachedUser(session.user); setAuthButton(); showAuthToast(`${tr('loginValid')} ${session.user.login}`, 2400); } else { state.user = null; setAuthButton(); showAuthToast(tr('loginNotActive'), 2600); } } catch { showAuthToast(tr('sessionCheckFailed'), 3200); } finally { setButtonBusy(button, false, 'checkLogin'); } }
async function handleAuthClick() { if (state.user) { signOut(); state.user = null; setAuthButton(); showAuthToast(tr('signedOut'), 1900); return; } openConnect(); await startGithubLogin(); }
async function copyDeviceCode() { const code = $('#oauthCode')?.dataset.code || ''; if (!code) return; try { await navigator.clipboard.writeText(code); const target = $('#copyCode span:first-child'); if (!target) return; target.textContent = tr('copied'); setTimeout(() => { target.textContent = tr('copyCode'); }, 1300); } catch { showAuthToast(tr('copyFailed'), 2200); } }
function postCard(post, index) { const labels = (post.labels || []).filter(Boolean).map(label => `<span>${safeText(label)}</span>`).join(''); const image = safeUrl(post.image); const media = image ? `<img class="post-image" src="${safeText(image)}" alt="${safeText(tr('imageAlt'))}" loading="lazy" decoding="async" referrerpolicy="no-referrer">` : `<img class="post-image post-image-fallback" src="fallback.svg" alt="${safeText(tr('imageAlt'))}" loading="lazy" decoding="async" aria-hidden="true">`; const href = issueRoute({ url: post.url }); return `<a class="post-card" href="${safeText(href)}" aria-label="${safeText(post.title)}"><div class="post-image-wrap${image ? '' : ' is-fallback'}">${media}</div><div class="post-body"><div class="post-top"><span class="post-number">${safeText(tr('post'))} ${String(index + 1).padStart(2, '0')}</span><time>${safeText(formatDate(post.updatedAt))}</time></div><div class="post-labels">${labels}</div><h3>${safeText(post.title || tr('postTitle'))}</h3><p>${safeText(post.excerpt || tr('noBody'))}</p><div class="post-foot"><span>#${post.number} · ${safeText(post.author)}</span><span>${tr('read')} <b>↗</b></span></div></div></a>`; }
function bindCardImages() { $$('.post-image:not(.post-image-fallback)').forEach(image => image.addEventListener('error', () => { image.closest('.post-image-wrap')?.classList.add('is-image-error'); image.removeAttribute('src'); image.setAttribute('aria-hidden', 'true'); }, { once: true })); }
function filterAndSort() { const query = state.query.trim().toLocaleLowerCase(); const items = state.posts.filter(post => `${post.title} ${post.excerpt} ${(post.labels || []).join(' ')} ${post.author}`.toLocaleLowerCase().includes(query)); items.sort((a, b) => state.sort === 'comments' ? Number(b.comments || 0) - Number(a.comments || 0) : state.sort === 'created' ? new Date(b.createdAt) - new Date(a.createdAt) : new Date(b.updatedAt) - new Date(a.updatedAt)); state.filteredPosts = items; return items; }
function renderPosts() { const posts = filterAndSort(); const visible = posts.slice(0, state.expanded ? posts.length : Math.min(PAGE_SIZE, posts.length)); const grid = $('#postGrid'); grid.innerHTML = visible.map(postCard).join(''); bindCardImages(); grid.setAttribute('aria-busy', 'false'); const total = posts.length; $('#postsCount').textContent = total ? `${visible.length} / ${total} ${tr('postsCount')}` : `0 ${tr('postsCount')}`; const hasAnyPosts = state.posts.length > 0; const showError = state.feedStatus === 'error' && !hasAnyPosts; const showEmpty = !showError && state.feedStatus !== 'loading' && total === 0; $('#postsEmpty').hidden = !showEmpty; $('#postsError').hidden = !showError; if (showEmpty) $('#postsEmptyText').textContent = hasAnyPosts ? tr('noResults') : tr('emptyFeed'); let status = tr('ready'); if (state.feedStatus === 'refresh-error' && hasAnyPosts) status = tr('refreshFailed'); else if (showEmpty) status = hasAnyPosts ? tr('noResults') : tr('noPosts'); else if (state.loadingAll) status = tr('loadingAll'); else if (state.feedStatus === 'loading') status = tr('loading'); $('#postsState').textContent = status; const moreButton = $('#loadMorePosts'); moreButton.hidden = total <= PAGE_SIZE && state.serverComplete; moreButton.disabled = state.loadingAll; moreButton.classList.toggle('is-loading', state.loadingAll); const label = moreButton.querySelector('[data-load-label]'); if (label) label.textContent = state.expanded ? tr('collapsePosts') : tr('loadMorePosts'); grid.classList.toggle('is-empty', visible.length === 0); }
function renderSkeletons() { $('#postGrid').innerHTML = Array.from({ length: PAGE_SIZE }, () => '<article class="post-skeleton"><div class="skeleton-image"></div><div class="skeleton-body"><span></span><span></span><b></b><i></i><i></i></div></article>').join(''); $('#postGrid').setAttribute('aria-busy', 'true'); $('#postsEmpty').hidden = true; $('#postsError').hidden = true; $('#loadMorePosts').hidden = true; }
async function loadPosts({ refresh = false } = {}) { if (state.loading) return; state.loading = true; if (!state.posts.length) { state.feedStatus = 'loading'; renderSkeletons(); } else if (refresh) { state.feedStatus = 'ready'; $('#postsState').textContent = tr('loading'); } try { const result = await fetchPostsInitial(); state.posts = result.posts || []; state.serverComplete = Boolean(result.complete); state.nextPage = result.nextPage || null; state.expanded = false; state.feedStatus = result.stale ? 'refresh-error' : 'ready'; renderPosts(); const badge = $('#rateBadge'); if (badge && result.rate?.remaining != null) { badge.hidden = false; badge.textContent = `${tr('rate')}: ${result.rate.remaining}`; } } catch (error) { console.error(error); state.feedStatus = state.posts.length ? 'refresh-error' : 'error'; renderPosts(); } finally { state.loading = false; } }
async function toggleMorePosts() { if (state.loadingAll) return; if (state.expanded) { state.expanded = false; renderPosts(); $('#posts').scrollIntoView(); return; } if (!state.serverComplete && state.nextPage) { state.loadingAll = true; renderPosts(); try { const result = await fetchRemainingPosts(state.nextPage, state.posts, page => { $('#postsState').textContent = `${tr('loadingAll')} ${page}`; }); state.posts = result.posts; state.serverComplete = true; state.nextPage = null; state.feedStatus = 'ready'; } catch (error) { console.error(error); state.feedStatus = state.posts.length ? 'refresh-error' : 'error'; } finally { state.loadingAll = false; } } state.expanded = true; renderPosts(); }
function seedCached() { const cache = getCachedPostsSnapshot(300000); if (!cache?.posts?.length) return false; state.posts = cache.posts; state.serverComplete = cache.complete !== false; state.nextPage = cache.nextPage || null; state.feedStatus = 'ready'; state.expanded = false; renderPosts(); return true; }
function setupScrollSpy() { if (!('IntersectionObserver' in window)) return; const sections = [['posts', $('#posts')], ['github', $('#github')]].filter(([, el]) => el); const observer = new IntersectionObserver(entries => { entries.forEach(entry => { if (!entry.isIntersecting) return; $$('.nav-link').forEach(link => link.classList.toggle('active', link.getAttribute('href')?.includes(entry.target.id))); }); }, { rootMargin: '-35% 0px -55% 0px', threshold: 0 }); sections.forEach(([, el]) => observer.observe(el)); }
function setupEvents() { $('#themeToggle')?.addEventListener('click', toggleTheme); $('#authTopButton')?.addEventListener('click', handleAuthClick); $('#closeConnect')?.addEventListener('click', closeConnect); $('#startGithubLogin')?.addEventListener('click', () => startGithubLogin()); $('#cancelGithubLogin')?.addEventListener('click', cancelGithubLogin); $('#checkLoginButton')?.addEventListener('click', checkLogin); $('#copyCode')?.addEventListener('click', copyDeviceCode); $('#refreshPosts')?.addEventListener('click', () => loadPosts({ refresh: true })); $('#retryPosts')?.addEventListener('click', () => loadPosts({ refresh: true })); $('#loadMorePosts')?.addEventListener('click', toggleMorePosts); $('#backTop')?.addEventListener('click', () => window.scrollTo({ top: 0, behavior: 'auto' })); $('#postSearch')?.addEventListener('input', event => { state.query = event.target.value; state.expanded = false; renderPosts(); }); $('#postSort')?.addEventListener('change', event => { state.sort = event.target.value; state.expanded = false; renderPosts(); }); $('#menuToggle')?.addEventListener('click', () => { const nav = $('#primaryNav'); const button = $('#menuToggle'); const open = nav.classList.toggle('open'); button.classList.toggle('is-open', open); button.setAttribute('aria-expanded', String(open)); }); $$('.nav-link').forEach(link => link.addEventListener('click', () => { $('#primaryNav')?.classList.remove('open'); $('#menuToggle')?.classList.remove('is-open'); $('#menuToggle')?.setAttribute('aria-expanded', 'false'); })); window.addEventListener('scroll', updateHeader, { passive: true }); window.addEventListener('resize', () => { if (window.innerWidth > 860) { $('#primaryNav')?.classList.remove('open'); $('#menuToggle')?.classList.remove('is-open'); $('#menuToggle')?.setAttribute('aria-expanded', 'false'); } }, { passive: true }); document.addEventListener('keydown', event => { if (event.key === 'Escape') { $('#primaryNav')?.classList.remove('open'); $('#menuToggle')?.classList.remove('is-open'); $('#menuToggle')?.setAttribute('aria-expanded', 'false'); const dialog = $('#connectDialog'); if (dialog?.open) closeConnect(); } }); setupScrollSpy(); updateHeader(); }
function setupLanguage() { initI18n(lang => { applyLanguage(lang); renderPosts(); setAuthButton(); }); }
function finishLoader() { const loader = $('#siteLoader'); if (loader) loader.remove(); }
function setupLinks() { const url = repoUrl(); $('#repoLink')?.setAttribute('href', url); $('#heroRepoLink')?.setAttribute('href', url); $('#footerRepoLink')?.setAttribute('href', url); $('#telegramLink')?.setAttribute('href', CONFIG.site.telegram); $('#heroTelegramLink')?.setAttribute('href', CONFIG.site.telegram); }
async function init() { initTheme(); initI18n(); setupLinks(); setupEvents(); setupLanguage(); $('#year').textContent = String(new Date().getFullYear()); const cached = seedCached(); await Promise.all([loadPosts({ refresh: Boolean(cached) }), restoreUser()]); applyLanguage(getLanguage()); setAuthButton(); if (cached) renderPosts(); await resumePendingLogin(); finishLoader(); }
init();
