import { CONFIG } from './config.js';
const API = 'https://api.github.com';
const baseHeaders = Object.freeze({ Accept: 'application/vnd.github+json', 'X-GitHub-Api-Version': CONFIG.github.apiVersion });
const path = (owner, repo, suffix = '') => `${API}/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}${suffix}`;
const sleep = ms => new Promise(resolve => setTimeout(resolve, ms));
export function repoUrl(owner = CONFIG.github.owner, repo = CONFIG.github.repo) { return `https://github.com/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}`; }
function readStorage(key) { try { return localStorage.getItem(key) || ''; } catch { return ''; } }
function writeStorage(key, value) { try { if (value) localStorage.setItem(key, value); else localStorage.removeItem(key); } catch {} }
function readCookie(name) { try { const prefix = `${encodeURIComponent(name)}=`; const row = document.cookie.split('; ').find(item => item.startsWith(prefix)); return row ? decodeURIComponent(row.slice(prefix.length)) : ''; } catch { return ''; } }
function writeCookie(name, value, maxAge = 2592000) { try { const secure = location.protocol === 'https:' ? '; Secure' : ''; document.cookie = `${encodeURIComponent(name)}=${encodeURIComponent(value)}; Max-Age=${maxAge}; Path=/; SameSite=Strict${secure}`; } catch {} }
function removeCookie(name) { writeCookie(name, '', 0); }
function readJsonStorage(key) { const raw = readStorage(key); if (!raw) return null; try { return JSON.parse(raw); } catch { return null; } }
function writeJsonStorage(key, value) { writeStorage(key, JSON.stringify(value)); }
function normalizeAuth(auth) { if (!auth?.accessToken) return null; return { accessToken: String(auth.accessToken), refreshToken: String(auth.refreshToken || ''), expiresAt: Number(auth.expiresAt || 0), tokenType: String(auth.tokenType || 'bearer'), scope: String(auth.scope || ''), createdAt: Number(auth.createdAt || Date.now()) }; }
function getAuth() { return normalizeAuth(readJsonStorage(CONFIG.storage.auth)); }
function setAuth(auth) { const value = normalizeAuth(auth); if (value) writeJsonStorage(CONFIG.storage.auth, value); else writeStorage(CONFIG.storage.auth, ''); }
function migrateLegacyAuth() { const current = getAuth(); if (current) return current; const token = readStorage(CONFIG.storage.legacyToken).trim(); if (!token) return null; const auth = { accessToken: token, refreshToken: '', expiresAt: 0, tokenType: 'bearer', scope: '', createdAt: Date.now() }; setAuth(auth); return auth; }
export function getCachedUser() { const raw = readCookie(CONFIG.storage.userCookie) || readCookie(CONFIG.storage.legacyUserCookie); if (!raw) return null; try { const user = JSON.parse(raw); return user && user.login ? user : null; } catch { return null; } }
export function setCachedUser(user) { if (!user?.login) { clearCachedUser(); return; } const snapshot = { id: user.id || null, login: user.login, name: user.name || '', avatar_url: user.avatar_url || '', html_url: user.html_url || '', type: user.type || 'User' }; writeCookie(CONFIG.storage.userCookie, JSON.stringify(snapshot)); }
export function clearCachedUser() { removeCookie(CONFIG.storage.userCookie); removeCookie(CONFIG.storage.legacyUserCookie); }
export function getAuthState() { return getAuth() || migrateLegacyAuth(); }
export function getAccessToken() { const auth = getAuthState(); if (!auth) return ''; if (auth.expiresAt && Date.now() >= auth.expiresAt) return ''; return auth.accessToken; }
export function isLoggedIn() { return Boolean(getAccessToken()); }
export function setAccessToken(token) { const clean = String(token || '').trim(); if (!clean) { setAuth(null); return; } setAuth({ accessToken: clean, refreshToken: '', expiresAt: 0, tokenType: 'bearer', scope: '', createdAt: Date.now() }); }
export function signOut() { setAuth(null); writeStorage(CONFIG.storage.legacyToken, ''); clearCachedUser(); }
function captureRate(response) { const remaining = response.headers.get('x-ratelimit-remaining'); const limit = response.headers.get('x-ratelimit-limit'); const reset = response.headers.get('x-ratelimit-reset'); return { remaining: remaining ? Number(remaining) : null, limit: limit ? Number(limit) : null, reset: reset ? Number(reset) : null }; }
export function getRateLabel(rate) { if (!rate || rate.remaining === null) return ''; return `${rate.remaining}/${rate.limit || 0}`; }
function mergeSignals(sourceSignal, timeout) { const controller = new AbortController(); const timer = setTimeout(() => controller.abort('timeout'), timeout); const abort = () => controller.abort(sourceSignal.reason || 'aborted'); if (sourceSignal) { if (sourceSignal.aborted) abort(); else sourceSignal.addEventListener('abort', abort, { once: true }); } return { signal: controller.signal, cleanup: () => { clearTimeout(timer); if (sourceSignal) sourceSignal.removeEventListener('abort', abort); } }; }
function authProxyUrl(target) { return `${CONFIG.github.oauth.authProxyPrefix}${encodeURIComponent(String(target || ''))}`; }
async function authFetch(url, options = {}) { return fetch(authProxyUrl(url), { ...options, cache: options.cache || 'no-store' }); }
function shouldRetry(response, method) { const normalized = String(method || 'GET').toUpperCase(); if (!['GET', 'HEAD'].includes(normalized)) return false; return response.status === 408 || response.status === 425 || response.status === 429 || response.status >= 500; }
async function executeGitHubFetch(url, options, headers) { const timeout = Number(options.timeout || CONFIG.github.requestTimeout); const method = String(options.method || 'GET').toUpperCase(); const retries = Number.isFinite(Number(options.retries)) ? Math.max(0, Number(options.retries)) : CONFIG.github.maxReadRetries; let attempt = 0; while (true) { const merged = mergeSignals(options.signal, timeout); try { const response = await fetch(url, { ...options, timeout: undefined, retries: undefined, requireAuth: undefined, signal: merged.signal, headers }); if (!shouldRetry(response, method) || attempt >= retries) return response; const retryAfter = Number(response.headers.get('retry-after')); const delay = Number.isFinite(retryAfter) && retryAfter > 0 ? Math.min(retryAfter * 1000, 8000) : Math.min(8000, 700 * (2 ** attempt)); attempt += 1; await sleep(delay); } catch (error) { if (options.signal?.aborted) throw error; if (attempt >= retries) { if (error?.name === 'AbortError') throw new Error(`GitHub request timed out after ${Math.round(timeout / 1000)}s.`); throw error; } attempt += 1; await sleep(Math.min(8000, 700 * (2 ** (attempt - 1)))); } finally { merged.cleanup(); } } }
export async function githubFetch(url, options = {}) { const requireAuth = Boolean(options.requireAuth); const token = requireAuth ? getAccessToken() : ''; if (requireAuth && !token) { const error = new Error('Not authenticated.'); error.status = 401; throw error; } const headers = { ...baseHeaders, ...(token ? { Authorization: `Bearer ${token}` } : {}), ...(options.headers || {}) }; const response = await executeGitHubFetch(url, options, headers); const rate = captureRate(response); if (!response.ok) { let detail = ''; let payload = null; try { payload = await response.clone().json(); detail = payload?.message || payload?.error_description || payload?.error || ''; } catch {} const error = new Error(detail || `GitHub returned ${response.status}`); error.status = response.status; error.rate = rate; error.payload = payload; if (response.status === 401 && requireAuth) signOut(); throw error; } response.rate = rate; return response; }
export async function fetchCurrentUser() { const token = getAccessToken(); if (!token) throw Object.assign(new Error('Not authenticated.'), { status: 401 }); const response = await githubFetch(`${API}/user`, { requireAuth: true, timeout: 12000, retries: 1 }); return { user: await response.json(), rate: response.rate }; }
export async function checkSession() { const token = getAccessToken(); if (!token) return { ok: false, user: null, reason: 'missing' }; try { const result = await fetchCurrentUser(); setCachedUser(result.user); return { ok: true, user: result.user, rate: result.rate, reason: 'valid' }; } catch (error) { if (error?.status === 401) { signOut(); return { ok: false, user: null, reason: 'unauthorized', error }; } if (!getAuthState()) return { ok: false, user: null, reason: 'missing', error }; throw error; } }
function excerpt(markdown = '') { return String(markdown).replace(/!\[[^\]]*\]\([^)]*\)/g, ' ').replace(/<[^>]+>/g, ' ').replace(/[#>*`_[\]]/g, ' ').replace(/https?:\/\/\S+/g, ' ').replace(/\s+/g, ' ').trim().slice(0, 230); }
export function firstImage(markdown = '') { const source = String(markdown); const markdownMatch = source.match(/!\[[^\]]*\]\((https?:\/\/[^\s)]+)(?:\s+"[^"]*")?\)/i); if (markdownMatch) return markdownMatch[1]; const htmlMatch = source.match(/<img[^>]+src=["'](https?:\/\/[^"']+)["']/i); if (htmlMatch) return htmlMatch[1]; const rawMatch = source.match(/https?:\/\/[^\s)"']+\.(?:png|jpe?g|gif|webp|avif|svg)(?:\?[^\s)]*)?/i); return rawMatch ? rawMatch[0] : ''; }
function normalizeIssue(issue) { return { id: issue.id, number: issue.number, title: issue.title || '', body: issue.body || '', bodyHtml: issue.body_html || '', url: issue.html_url, apiUrl: issue.url, image: firstImage(issue.body || ''), excerpt: excerpt(issue.body || ''), labels: (issue.labels || []).filter(Boolean).slice(0, 8).map(label => typeof label === 'string' ? label : label.name), updatedAt: issue.updated_at, createdAt: issue.created_at, author: issue.user?.login || 'GitHub', authorUrl: issue.user?.html_url || '#', comments: Number(issue.comments || 0), reactions: issue.reactions || {}, state: issue.state || 'open', locked: Boolean(issue.locked), milestone: issue.milestone?.title || '', assignees: (issue.assignees || []).map(user => user.login), pullRequest: Boolean(issue.pull_request) }; }
function cacheKey() { return `${CONFIG.github.owner}/${CONFIG.github.repo}`; }
function readPostsCache() { const primary = readJsonStorage(CONFIG.storage.postsCache); if (primary?.key === cacheKey()) return primary; const legacy = readJsonStorage(CONFIG.storage.legacyPostsCache); if (legacy?.key === cacheKey() && Array.isArray(legacy.posts)) return { ...legacy, complete: true }; return null; }
function writePostsCache(posts, complete = true, nextPage = null) { try { writeJsonStorage(CONFIG.storage.postsCache, { key: cacheKey(), savedAt: Date.now(), posts, complete, nextPage }); } catch {} }
export function getCachedPostsSnapshot(maxAge = 300000) { const cache = readPostsCache(); return cache && Array.isArray(cache.posts) && Date.now() - Number(cache.savedAt || 0) < maxAge ? cache : null; }
function nextPageFrom(response, currentPage) { const link = response.headers.get('link') || ''; const match = link.match(/<([^>]+)>;\s*rel="next"/i); if (!match) return null; try { const url = new URL(match[1]); const page = Number(url.searchParams.get('page') || 0); return Number.isFinite(page) && page > currentPage ? page : null; } catch { return null; } }
async function fetchPostsPage(page = 1) { const url = new URL(`${path(CONFIG.github.owner, CONFIG.github.repo)}/issues`); url.searchParams.set('state', CONFIG.github.issueState); url.searchParams.set('sort', 'updated'); url.searchParams.set('direction', 'desc'); url.searchParams.set('per_page', String(CONFIG.github.initialPageSize)); url.searchParams.set('page', String(page)); const response = await githubFetch(url.toString(), { timeout: CONFIG.github.requestTimeout, retries: CONFIG.github.maxReadRetries }); const issues = await response.json(); const posts = Array.isArray(issues) ? issues.filter(issue => !issue.pull_request).map(normalizeIssue) : []; return { posts, nextPage: nextPageFrom(response, page), rate: response.rate }; }
export async function fetchPostsInitial() { const cached = getCachedPostsSnapshot(300000); try { const result = await fetchPostsPage(1); writePostsCache(result.posts, !result.nextPage, result.nextPage); return { posts: result.posts, complete: !result.nextPage, nextPage: result.nextPage, cached: false, stale: false, rate: result.rate }; } catch (error) { if (cached) return { posts: cached.posts, complete: cached.complete !== false, nextPage: cached.nextPage || null, cached: true, stale: true, rate: null, error }; throw error; } }
export async function fetchRemainingPosts(startPage, existingPosts = [], onProgress = () => {}) { let page = Number(startPage || 0); let posts = Array.isArray(existingPosts) ? [...existingPosts] : []; let lastRate = null; if (!page) return { posts, complete: true, nextPage: null, rate: lastRate }; while (page) { onProgress(page); const result = await fetchPostsPage(page); lastRate = result.rate; posts = [...posts, ...result.posts]; page = result.nextPage; writePostsCache(posts, !page, page); } return { posts, complete: true, nextPage: null, rate: lastRate }; }
export function parseIssueUrl(value) { try { const url = new URL(String(value)); if (!['github.com', 'www.github.com'].includes(url.hostname.toLowerCase())) return null; const parts = url.pathname.split('/').filter(Boolean); if (parts.length !== 4 || parts[2].toLowerCase() !== 'issues' || !/^\d+$/.test(parts[3])) return null; return { owner: parts[0], repo: parts[1], number: Number(parts[3]), url: `https://github.com/${parts[0]}/${parts[1]}/issues/${parts[3]}` }; } catch { return null; } }
export async function fetchIssue(target) { const response = await githubFetch(`${path(target.owner, target.repo)}/issues/${target.number}`, { headers: { Accept: 'application/vnd.github.full+json' }, retries: 1 }); return { data: await response.json(), rate: response.rate }; }
export async function fetchIssueComments(target, page = 1, perPage = CONFIG.github.initialCommentsPerPage, direction = 'asc') { const response = await githubFetch(`${path(target.owner, target.repo)}/issues/${target.number}/comments?per_page=${perPage}&direction=${direction}&page=${page}`, { headers: { Accept: 'application/vnd.github.full+json' }, retries: 1 }); const comments = await response.json(); return { comments: Array.isArray(comments) ? comments : [], rate: response.rate, hasMore: Array.isArray(comments) && comments.length === perPage }; }
export async function fetchIssueReactions(target, page = 1) { const response = await githubFetch(`${path(target.owner, target.repo)}/issues/${target.number}/reactions?per_page=100&page=${page}`, { headers: { Accept: 'application/vnd.github+json' }, retries: 1 }); const data = await response.json(); return { reactions: Array.isArray(data) ? data : [], rate: response.rate, hasMore: Array.isArray(data) && data.length === 100 }; }
export async function fetchAllIssueReactions(target) { const output = []; let page = 1; while (page <= 20) { const result = await fetchIssueReactions(target, page); output.push(...result.reactions); if (!result.hasMore) break; page += 1; } return output; }
export async function createIssueReaction(target, content) { const response = await githubFetch(`${path(target.owner, target.repo)}/issues/${target.number}/reactions`, { method: 'POST', requireAuth: true, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ content }), retries: 0 }); return response.json(); }
export async function deleteIssueReaction(target, reactionId) { await githubFetch(`${path(target.owner, target.repo)}/issues/${target.number}/reactions/${reactionId}`, { method: 'DELETE', requireAuth: true, retries: 0 }); }
export async function createIssueComment(target, body) { const response = await githubFetch(`${path(target.owner, target.repo)}/issues/${target.number}/comments`, { method: 'POST', requireAuth: true, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ body }), retries: 0 }); return response.json(); }
export async function updateIssueComment(target, commentId, body) { const response = await githubFetch(`${path(target.owner, target.repo)}/issues/comments/${commentId}`, { method: 'PATCH', requireAuth: true, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ body }), retries: 0 }); return response.json(); }
export async function deleteIssueComment(target, commentId) { await githubFetch(`${path(target.owner, target.repo)}/issues/comments/${commentId}`, { method: 'DELETE', requireAuth: true, retries: 0 }); }
export function reactionTypes() { return [{ key: '+1', icon: '👍' }, { key: 'heart', icon: '♥' }, { key: 'hooray', icon: '🎉' }, { key: 'rocket', icon: '🚀' }, { key: 'laugh', icon: '😄' }, { key: 'eyes', icon: '👀' }]; }
export function getReactionCount(reactions = {}) { return Object.values(reactions).filter(value => Number.isFinite(Number(value))).reduce((sum, value) => sum + Number(value), 0); }
export function issueRoute(target) { return `post.html?post=${encodeURIComponent(target.url)}`; }
function pendingFlowSnapshot(flow) { return { deviceCode: String(flow.deviceCode || ''), userCode: String(flow.userCode || ''), verificationUri: String(flow.verificationUri || CONFIG.github.oauth.verificationUrl), expiresIn: Math.max(0, Number(flow.expiresIn || 900)), interval: Math.max(5, Number(flow.interval || 5)), createdAt: Number(flow.createdAt || Date.now()), expiresAt: Number(flow.expiresAt || (Date.now() + Number(flow.expiresIn || 900) * 1000)) }; }
export function getPendingDeviceFlow() { const flow = readJsonStorage(CONFIG.storage.oauthFlow); if (!flow?.deviceCode || !flow.userCode) return null; const normalized = pendingFlowSnapshot(flow); if (Date.now() >= normalized.expiresAt) { clearPendingDeviceFlow(); return null; } return normalized; }
export function savePendingDeviceFlow(flow) { const normalized = pendingFlowSnapshot(flow); if (!normalized.deviceCode || !normalized.userCode) return null; writeJsonStorage(CONFIG.storage.oauthFlow, normalized); return normalized; }
export function clearPendingDeviceFlow() { writeStorage(CONFIG.storage.oauthFlow, ''); }
function pollLockId() { if (!pollLockId.value) pollLockId.value = `${Date.now()}-${Math.random().toString(36).slice(2)}`; return pollLockId.value; }
function acquirePollLock(ttl = 9000) { const now = Date.now(); const current = readJsonStorage(CONFIG.storage.oauthPollLock); if (current && Number(current.expiresAt || 0) > now && current.owner !== pollLockId()) return false; writeJsonStorage(CONFIG.storage.oauthPollLock, { owner: pollLockId(), expiresAt: now + ttl }); return true; }
function releasePollLock() { const current = readJsonStorage(CONFIG.storage.oauthPollLock); if (current?.owner === pollLockId()) writeStorage(CONFIG.storage.oauthPollLock, ''); }
export async function beginDeviceFlow() { if (!CONFIG.github.oauth.clientId) throw new Error('GitHub OAuth Client ID is not configured.'); const body = new URLSearchParams({ client_id: CONFIG.github.oauth.clientId, scope: CONFIG.github.oauth.scope }); const response = await authFetch(CONFIG.github.oauth.deviceCodeUrl, { method: 'POST', headers: { Accept: 'application/json', 'Content-Type': 'application/x-www-form-urlencoded' }, body }); let data = null; try { data = await response.json(); } catch {} if (!response.ok || !data?.device_code) throw new Error(data?.error_description || data?.error || `GitHub device authorization failed (${response.status})`); const createdAt = Date.now(); return savePendingDeviceFlow({ deviceCode: data.device_code, userCode: data.user_code, verificationUri: data.verification_uri || CONFIG.github.oauth.verificationUrl, expiresIn: Number(data.expires_in || 900), interval: Math.max(5, Number(data.interval || 5)), createdAt, expiresAt: createdAt + Number(data.expires_in || 900) * 1000 }); }
export async function pollDeviceFlow(flow, { signal, onPending = () => {}, onSlowDown = () => {}, onSuccess = () => {} } = {}) { if (!CONFIG.github.oauth.clientId) throw new Error('GitHub OAuth Client ID is not configured.'); const normalized = pendingFlowSnapshot(flow); const deadline = normalized.expiresAt; let interval = Math.max(5, Number(normalized.interval || 5)); while (Date.now() < deadline) { if (signal?.aborted) throw new DOMException('Login cancelled.', 'AbortError'); await sleep(interval * 1000); if (signal?.aborted) throw new DOMException('Login cancelled.', 'AbortError'); if (Date.now() >= deadline) break; if (!acquirePollLock()) { await sleep(900); continue; } try { const body = new URLSearchParams({ client_id: CONFIG.github.oauth.clientId, device_code: normalized.deviceCode, grant_type: 'urn:ietf:params:oauth:grant-type:device_code' }); const response = await authFetch(CONFIG.github.oauth.tokenUrl, { method: 'POST', headers: { Accept: 'application/json', 'Content-Type': 'application/x-www-form-urlencoded' }, body, signal }); let data = null; try { data = await response.json(); } catch {} if (data?.access_token) { const auth = { accessToken: data.access_token, refreshToken: data.refresh_token || '', expiresAt: data.expires_in ? Date.now() + Number(data.expires_in) * 1000 - 60000 : 0, tokenType: data.token_type || 'bearer', scope: data.scope || CONFIG.github.oauth.scope, createdAt: Date.now() }; setAuth(auth); clearPendingDeviceFlow(); const result = await fetchCurrentUser(); setCachedUser(result.user); onSuccess(result.user); return result.user; } const code = data?.error || (response.ok ? '' : `oauth_${response.status}`); if (code === 'authorization_pending') { onPending(); continue; } if (code === 'slow_down') { interval = Math.max(interval + 5, Number(data?.interval || interval + 5)); onSlowDown(interval); continue; } if (code === 'expired_token' || code === 'token_expired') { clearPendingDeviceFlow(); throw new Error('GitHub authorization code expired.'); } if (code === 'access_denied') { clearPendingDeviceFlow(); throw new Error('GitHub authorization was denied.'); } clearPendingDeviceFlow(); throw new Error(data?.error_description || data?.error || `GitHub OAuth error (${response.status})`); } finally { releasePollLock(); } } clearPendingDeviceFlow(); throw new Error('GitHub authorization timed out.'); }
