import { CONFIG } from './config.js';
import { checkSession, clearPendingDeviceFlow, createIssueComment, createIssueReaction, deleteIssueComment, deleteIssueReaction, fetchAllIssueReactions, fetchIssue, fetchIssueComments, firstImage, getCachedUser, getPendingDeviceFlow, getReactionCount, parseIssueUrl, reactionTypes, setCachedUser, signOut, updateIssueComment, isLoggedIn, beginDeviceFlow, pollDeviceFlow } from './github.js';
import { applyLanguage, initI18n, tr, getLanguage } from './i18n.js';
const $ = (selector, scope = document) => scope.querySelector(selector);
const $$ = (selector, scope = document) => [...scope.querySelectorAll(selector)];
const state = { target: null, issue: null, reactions: [], comments: [], commentsPage: 1, commentsHasMore: false, commentSort: 'asc', user: null, busy: false, editingComment: null, oauthAbort: null };
const sleep = ms => new Promise(resolve => setTimeout(resolve, ms));
function safeText(value = '') { return String(value).replace(/[&<>'"]/g, ch => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#039;', '"': '&quot;' }[ch])); }
function safeUrl(value = '') { try { const url = new URL(value, location.href); return ['http:', 'https:'].includes(url.protocol) ? url.href : ''; } catch { return ''; } }
function formatDate(value, withTime = false) { const date = new Date(value); if (Number.isNaN(date.getTime())) return '—'; return new Intl.DateTimeFormat(tr('locale'), withTime ? { dateStyle: 'medium', timeStyle: 'short' } : { month: 'long', day: 'numeric', year: 'numeric' }).format(date); }
function initTheme() { let theme = ''; try { theme = localStorage.getItem(CONFIG.storage.theme) || localStorage.getItem(CONFIG.storage.legacyTheme) || ''; } catch {} setTheme(theme || 'light'); }
function setTheme(theme) { const value = theme === 'dark' ? 'dark' : 'light'; document.documentElement.dataset.theme = value; document.documentElement.style.colorScheme = value; document.querySelector('meta[name="theme-color"]')?.setAttribute('content', value === 'dark' ? '#0b0d0f' : '#f3f4f5'); try { localStorage.setItem(CONFIG.storage.theme, value); } catch {} }
function toggleTheme() { setTheme(document.documentElement.dataset.theme === 'dark' ? 'light' : 'dark'); }
function updateHeader() { $('#topbar')?.classList.toggle('is-scrolled', window.scrollY > 16); }
function showAuthToast(message = tr('loginRequired'), duration = 2600) { const toast = $('#authToast'); if (!toast) return; const label = toast.querySelector('[data-auth-message]') || toast.querySelector('[data-i18n]'); if (label) label.textContent = message; toast.hidden = false; clearTimeout(showAuthToast.timer); showAuthToast.timer = setTimeout(() => { toast.hidden = true; }, duration); }
function showError(title, detail = '') { $('#readerError').hidden = false; $('#postReader').hidden = true; $('#errorTitle').textContent = title; $('#errorText').textContent = detail || tr('unavailableText'); }
function renderSafeHtml(target, html, fallback = '') { const source = String(html || fallback || '').trim(); target.innerHTML = source || `<p>${safeText(tr('noBody'))}</p>`; target.querySelectorAll('a').forEach(a => { a.target = '_blank'; a.rel = 'noreferrer noopener'; }); target.querySelectorAll('img').forEach(img => { img.loading = 'lazy'; img.decoding = 'async'; img.referrerPolicy = 'no-referrer'; }); }
function setSeo(issue) { const image = safeUrl(firstImage(issue?.body || '')); const title = `${issue.title || 'Post'} — ${CONFIG.site.name}`; document.title = title; document.querySelector('meta[name="description"]')?.setAttribute('content', `${issue.title || ''}. ${tr('metaPost')}`); document.querySelector('meta[property="og:title"]')?.setAttribute('content', title); document.querySelector('meta[property="og:description"]')?.setAttribute('content', issue.body?.slice(0, 190) || tr('metaPost')); document.querySelector('meta[property="og:url"]')?.setAttribute('content', issue.html_url || location.href); const ogImage = document.querySelector('meta[property="og:image"]'); if (ogImage) { if (image) ogImage.setAttribute('content', image); else ogImage.removeAttribute('content'); } document.querySelector('link[rel="canonical"]')?.setAttribute('href', location.href); let schema = $('#postSchema'); if (!schema) { schema = document.createElement('script'); schema.type = 'application/ld+json'; schema.id = 'postSchema'; document.head.appendChild(schema); } schema.textContent = JSON.stringify({ '@context': 'https://schema.org', '@type': 'Article', headline: issue.title, description: issue.body?.slice(0, 190) || '', image: image ? [image] : [], datePublished: issue.created_at, dateModified: issue.updated_at, author: { '@type': 'Person', name: issue.user?.login || 'GitHub' }, publisher: { '@type': 'Organization', name: CONFIG.site.name }, mainEntityOfPage: { '@type': 'WebPage', '@id': location.href } }); }
function currentReaction(key) { const login = state.user?.login; return login ? state.reactions.find(reaction => reaction.content === key && reaction.user?.login === login) : null; }
function renderReactions() { const root = $('#postReactions'); const counts = state.issue?.reactions || {}; root.innerHTML = `${reactionTypes().map(type => { const mine = currentReaction(type.key); const count = Number(counts[type.key] || 0); return `<button class="reaction-button${mine ? ' is-active' : ''}" type="button" data-reaction="${safeText(type.key)}" aria-pressed="${Boolean(mine)}"><span>${type.icon}</span><b>${count}</b></button>`; }).join('')}<span class="reaction-total">${tr('total')}: ${getReactionCount(counts)}</span>`; $$('[data-reaction]', root).forEach(button => button.addEventListener('click', () => toggleReaction(button.dataset.reaction))); $('#reactionCount').textContent = String(getReactionCount(counts)); }
function renderIssue() { const issue = state.issue; $('#postReader').hidden = false; $('#postNumber').textContent = `${tr('post')} #${issue.number}`; $('#postDate').textContent = formatDate(issue.updated_at, true); $('#postState').textContent = issue.locked ? tr('locked') : issue.state === 'closed' ? tr('closed') : tr('open'); $('#postTitle').textContent = issue.title || tr('postTitle'); $('#postByline').innerHTML = `<span>${safeText(tr('author'))}:</span> <a href="${safeText(safeUrl(issue.user?.html_url) || '#')}" target="_blank" rel="noreferrer noopener">${safeText(issue.user?.login || 'GitHub')}</a><span>·</span><span>${safeText(formatDate(issue.created_at))}</span>`; $('#postLabels').innerHTML = (issue.labels || []).map(label => `<span>${safeText(label.name || label)}</span>`).join(''); $('#commentCount').textContent = String(issue.comments || 0); $('#issueLinkLabel').textContent = `#${issue.number}`; $('#openGithub').href = safeUrl(issue.html_url) || '#'; renderSafeHtml($('#postContent'), issue.body_html, issue.body); renderReactions(); setSeo(issue); }
function renderComments() { const root = $('#commentsList'); if (!state.comments.length) root.innerHTML = `<div class="comments-empty">${safeText(tr('noComments'))}</div>`; else { root.innerHTML = state.comments.map(comment => { const mine = state.user?.login && comment.user?.login === state.user.login; const reactions = comment.reactions || {}; return `<article class="comment-card"><div class="comment-head"><div class="comment-user"><img class="comment-avatar" src="${safeText(safeUrl(comment.user?.avatar_url) || 'fallback.svg')}" alt="" loading="lazy" referrerpolicy="no-referrer"><div><a href="${safeText(safeUrl(comment.user?.html_url) || '#')}" target="_blank" rel="noreferrer noopener">${safeText(comment.user?.login || 'GitHub')}</a><span>${safeText(formatDate(comment.created_at, true))}</span></div></div><time>${comment.updated_at !== comment.created_at ? safeText(tr('edited')) : ''}</time></div><div class="comment-body" data-body-id="${safeText(comment.id)}"></div><div class="comment-actions"><div class="comment-actions-left"><span class="tiny-action">👍 ${Number(reactions['+1'] || 0)}</span><span class="tiny-action">♥ ${Number(reactions.heart || 0)}</span></div><div class="comment-actions-right">${mine ? `<button class="tiny-action" type="button" data-edit="${safeText(comment.id)}">${tr('edit')}</button><button class="tiny-action" type="button" data-delete="${safeText(comment.id)}">${tr('delete')}</button>` : ''}</div></div></article>`; }).join(''); state.comments.forEach(comment => { const body = $(`[data-body-id="${String(comment.id)}"]`); if (body) renderSafeHtml(body, comment.body_html, comment.body); }); } $('#commentsStatus').textContent = `${state.comments.length}${state.issue?.comments ? ` / ${state.issue.comments}` : ''} ${tr('comments')}`; $('#loadMoreComments').hidden = !state.commentsHasMore; $$('[data-edit]').forEach(button => button.addEventListener('click', () => startEdit(button.dataset.edit))); $$('[data-delete]').forEach(button => button.addEventListener('click', () => deleteComment(button.dataset.delete))); }
async function loadComments({ reset = false } = {}) { if (!state.target) return; const page = reset ? 1 : state.commentsPage; const result = await fetchIssueComments(state.target, page, CONFIG.github.initialCommentsPerPage, state.commentSort); const incoming = Array.isArray(result.comments) ? result.comments : []; state.commentsPage = page; state.comments = reset || page === 1 ? incoming : [...state.comments, ...incoming]; state.commentsHasMore = result.hasMore; $('#rateLabel').textContent = result.rate?.remaining ?? '—'; renderComments(); }
async function refreshComments() { if (state.busy) return; state.busy = true; try { await loadComments({ reset: true }); $('#composerStatus').textContent = ''; } catch (error) { $('#composerStatus').textContent = error.message || tr('unavailable'); } finally { state.busy = false; updateAuthUi(); } }
async function loadMoreComments() { if (!state.commentsHasMore || state.busy) return; state.busy = true; try { state.commentsPage += 1; await loadComments(); } catch (error) { state.commentsPage = Math.max(1, state.commentsPage - 1); $('#composerStatus').textContent = error.message || tr('unavailable'); } finally { state.busy = false; updateAuthUi(); } }
function setButtonBusy(button, busy, labelKey) { if (!button) return; button.disabled = busy; button.setAttribute('aria-busy', String(busy)); const label = button.querySelector('span:first-child'); if (!label) return; if (busy) { if (!button.dataset.idleLabel) button.dataset.idleLabel = label.textContent; label.textContent = tr(labelKey); } else { label.textContent = button.dataset.idleLabel || label.textContent; delete button.dataset.idleLabel; } }
function updateAuthUi() { const logged = Boolean(state.user); $('#authButton').hidden = logged; $('#logoutButton').hidden = !logged; $('#commentInput').disabled = state.busy || !logged; const valid = $('#commentInput').value.trim().length > 0; $('#submitComment').disabled = state.busy || !logged || !valid; $('#composerUser').textContent = logged ? `${tr('commentAs')} ${state.user.login}` : tr('connectFirst'); $('#authTitle').textContent = logged ? `${tr('connectedAs')} ${state.user.login}` : tr('connectTitle'); $('#authText').textContent = logged ? tr('commentAs') : tr('connectText'); const top = $('#authTopButton'); if (top) { top.classList.toggle('is-connected', logged); top.setAttribute('aria-pressed', String(logged)); const label = top.querySelector('[data-auth-label]'); if (label) label.textContent = logged ? `${tr('connectedAs')} ${state.user.login}` : tr('navConnect'); } $('#commentCounter').textContent = `${$('#commentInput').value.length} / 65536`; }
async function restoreUser() { if (!isLoggedIn()) { state.user = null; updateAuthUi(); return; } const cached = getCachedUser(); if (cached) { state.user = cached; updateAuthUi(); } try { const session = await checkSession(); if (session.ok) state.user = session.user; else state.user = null; } catch { if (!cached || !isLoggedIn()) state.user = null; } updateAuthUi(); renderReactions(); renderComments(); }
function openConnect() { const dialog = $('#connectDialog'); if (!dialog) return; const pending = getPendingDeviceFlow(); if (pending) { $('#oauthStartView').hidden = true; $('#oauthPendingView').hidden = false; setLoginPendingUI(pending); } else { $('#oauthStartView').hidden = false; $('#oauthPendingView').hidden = true; $('#oauthStatus').textContent = tr('loginWaiting'); $('#oauthStartStatus').textContent = ''; $('#oauthCode').textContent = '---- ----'; $('#oauthCode').removeAttribute('data-code'); $('#oauthCountdown').textContent = ''; $('#verificationLink').href = CONFIG.github.oauth.verificationUrl; } if (typeof dialog.showModal === 'function') { if (!dialog.open) dialog.showModal(); } else dialog.setAttribute('open', ''); }
function closeConnect() { const dialog = $('#connectDialog'); if (typeof dialog?.close === 'function') dialog.close(); else dialog?.removeAttribute('open'); clearInterval(setLoginPendingUI.timer); }
function cancelGithubLogin() { if (state.oauthAbort) { state.oauthAbort.abort(); state.oauthAbort = null; } clearPendingDeviceFlow(); closeConnect(); }
function setLoginPendingUI(flow) { const expiresAt = Number(flow.expiresAt || Date.now() + Number(flow.expiresIn || 900) * 1000); $('#oauthStartView').hidden = true; $('#oauthPendingView').hidden = false; $('#oauthCode').textContent = flow.userCode || '---- ----'; $('#oauthCode').dataset.code = flow.userCode || ''; $('#verificationLink').href = flow.verificationUri || CONFIG.github.oauth.verificationUrl; $('#oauthStatus').textContent = tr('loginPending'); const countdown = $('#oauthCountdown'); clearInterval(setLoginPendingUI.timer); const tick = () => { const left = Math.max(0, Math.ceil((expiresAt - Date.now()) / 1000)); if (countdown) countdown.textContent = left ? `${Math.floor(left / 60)}:${String(left % 60).padStart(2, '0')}` : '0:00'; if (!left) clearInterval(setLoginPendingUI.timer); }; tick(); setLoginPendingUI.timer = setInterval(tick, 1000); }
function openVerificationTab() { try { const popup = window.open('', 'nullspire-github-login'); if (popup) { try { popup.opener = null; } catch {} return popup; } } catch {} return null; }
async function runGithubLogin(flow, controller, popup = null) { setLoginPendingUI(flow); if (popup) popup.location.href = flow.verificationUri || CONFIG.github.oauth.verificationUrl; const user = await pollDeviceFlow(flow, { signal: controller.signal, onPending: () => $('#oauthStatus').textContent = tr('loginPending'), onSlowDown: interval => $('#oauthStatus').textContent = `${tr('loginSlow')} ${interval}s`, onSuccess: () => $('#oauthStatus').textContent = tr('loginSuccess') }); const session = await checkSession(); if (!session.ok) throw new Error(tr('loginVerificationFailed')); state.user = session.user || user; setCachedUser(state.user); updateAuthUi(); renderReactions(); renderComments(); closeConnect(); showAuthToast(`${tr('loginSuccess')} ${state.user.login}`, 2400); }
async function startGithubLogin({ autoOpen = true } = {}) { if (state.oauthAbort) { openConnect(); return; } if (!CONFIG.github.oauth.clientId) { $('#oauthStatus').textContent = tr('oauthClientMissing'); return; } const controller = new AbortController(); let popup = null; state.oauthAbort = controller; const button = $('#startGithubLogin'); try { if (autoOpen) popup = openVerificationTab(); setButtonBusy(button, true, 'loginPleaseWait'); $('#oauthStartStatus').textContent = tr('loginPleaseWait'); $('#oauthStatus').textContent = tr('loginPleaseWait'); const pending = getPendingDeviceFlow(); const flow = pending || await beginDeviceFlow(); await runGithubLogin(flow, controller, popup); } catch (error) { if (popup && !popup.closed) { try { popup.close(); } catch {} } if (error?.name === 'AbortError') { $('#oauthStatus').textContent = tr('loginCancelled'); $('#oauthStartStatus').textContent = tr('loginCancelled'); } else { const message = error.message || tr('loginCancelled'); $('#oauthStatus').textContent = message; $('#oauthStartStatus').textContent = message; } } finally { state.oauthAbort = null; setButtonBusy(button, false, 'loginStart'); clearInterval(setLoginPendingUI.timer); if (!state.user && !getPendingDeviceFlow()) { $('#oauthStartView').hidden = false; $('#oauthPendingView').hidden = true; } } }
async function resumePendingLogin() { if (state.user || state.oauthAbort) return; const flow = getPendingDeviceFlow(); if (!flow) return; openConnect(); await startGithubLogin({ autoOpen: false }); }
async function checkLogin() { const button = $('#checkLoginButton') || $('#checkLoginDialogButton'); if (!button || button.disabled) return; setButtonBusy(button, true, 'checkingLogin'); try { const session = await checkSession(); if (session.ok) { state.user = session.user; setCachedUser(session.user); updateAuthUi(); showAuthToast(`${tr('loginValid')} ${session.user.login}`, 2400); } else { state.user = null; updateAuthUi(); showAuthToast(tr('loginNotActive'), 2600); } } catch { showAuthToast(tr('sessionCheckFailed'), 3200); } finally { setButtonBusy(button, false, 'checkLogin'); } }
async function copyDeviceCode() { const code = $('#oauthCode')?.dataset.code || ''; if (!code) return; try { await navigator.clipboard.writeText(code); const target = $('#copyCode span:first-child'); if (!target) return; target.textContent = tr('copied'); setTimeout(() => { target.textContent = tr('copyCode'); }, 1300); } catch { showAuthToast(tr('copyFailed'), 2200); } }
async function requireAuth() { if (!state.user || !isLoggedIn()) { showAuthToast(tr('loginRequired')); openConnect(); await startGithubLogin(); if (!state.user) return false; } try { const session = await checkSession(); if (session.ok) { state.user = session.user; setCachedUser(session.user); updateAuthUi(); return true; } state.user = null; updateAuthUi(); showAuthToast(tr('sessionExpired'), 3000); return false; } catch { showAuthToast(tr('sessionCheckFailed'), 3200); return false; } }
function startEdit(commentId) { const comment = state.comments.find(item => String(item.id) === String(commentId)); if (!comment || state.user?.login !== comment.user?.login) return; state.editingComment = comment.id; const input = $('#commentInput'); input.value = comment.body || ''; $('#cancelEdit').hidden = false; $('#submitComment').querySelector('span:first-child').textContent = tr('updateComment'); $('#composerStatus').textContent = ''; input.focus(); updateAuthUi(); input.scrollIntoView({ behavior: 'auto', block: 'center' }); }
function cancelEdit() { state.editingComment = null; const input = $('#commentInput'); input.value = ''; $('#cancelEdit').hidden = true; const text = $('#submitComment')?.querySelector('span:first-child'); if (text) text.textContent = tr('publish'); updateAuthUi(); }
async function toggleReaction(key) { if (state.busy || !(await requireAuth())) return; const current = currentReaction(key); state.busy = true; updateAuthUi(); try { if (current) await deleteIssueReaction(state.target, current.id); else await createIssueReaction(state.target, key); const latest = await fetchAllIssueReactions(state.target); state.reactions = latest; const amount = Number(state.issue.reactions?.[key] || 0); if (state.issue.reactions) state.issue.reactions[key] = current ? Math.max(0, amount - 1) : amount + 1; renderReactions(); } catch (error) { if (error?.status === 401) { state.user = null; updateAuthUi(); showAuthToast(tr('sessionExpired'), 3000); } else $('#composerStatus').textContent = error.message || tr('unavailable'); } finally { state.busy = false; updateAuthUi(); } }
async function submitComment() { if (state.busy || !(await requireAuth())) return; const input = $('#commentInput'); const body = input.value.trim(); if (!body) return; const editingId = state.editingComment; state.busy = true; updateAuthUi(); $('#composerStatus').textContent = editingId ? tr('editing') : tr('publishing'); try { if (editingId) { await updateIssueComment(state.target, editingId, body); $('#composerStatus').textContent = tr('edited'); } else { await createIssueComment(state.target, body); state.issue.comments = Number(state.issue.comments || 0) + 1; $('#composerStatus').textContent = tr('published'); } cancelEdit(); await loadComments({ reset: true }); $('#commentCount').textContent = String(state.issue.comments || 0); } catch (error) { if (error?.status === 401) { state.user = null; updateAuthUi(); showAuthToast(tr('sessionExpired'), 3000); } else $('#composerStatus').textContent = error.message || tr('unavailable'); } finally { state.busy = false; updateAuthUi(); } }
async function deleteComment(commentId) { if (state.busy || !(await requireAuth())) return; const comment = state.comments.find(item => String(item.id) === String(commentId)); if (!comment || comment.user?.login !== state.user?.login || !window.confirm(tr('confirmDelete'))) return; state.busy = true; updateAuthUi(); $('#composerStatus').textContent = tr('deleting'); try { await deleteIssueComment(state.target, commentId); state.comments = state.comments.filter(item => String(item.id) !== String(commentId)); state.issue.comments = Math.max(0, Number(state.issue.comments || 0) - 1); $('#commentCount').textContent = String(state.issue.comments); renderComments(); $('#composerStatus').textContent = tr('deleted'); } catch (error) { if (error?.status === 401) { state.user = null; updateAuthUi(); showAuthToast(tr('sessionExpired'), 3000); } else $('#composerStatus').textContent = error.message || tr('unavailable'); } finally { state.busy = false; updateAuthUi(); } }
function setupEvents() { $('#themeToggle')?.addEventListener('click', toggleTheme); $('#authTopButton')?.addEventListener('click', async () => { if (state.user) { signOut(); state.user = null; cancelEdit(); updateAuthUi(); renderReactions(); renderComments(); showAuthToast(tr('signedOut'), 1900); } else { openConnect(); await startGithubLogin(); } }); $('#authButton')?.addEventListener('click', async () => { openConnect(); await startGithubLogin(); }); $('#logoutButton')?.addEventListener('click', () => { signOut(); state.user = null; cancelEdit(); updateAuthUi(); renderReactions(); renderComments(); showAuthToast(tr('signedOut'), 1900); }); $('#closeConnect')?.addEventListener('click', closeConnect); $('#startGithubLogin')?.addEventListener('click', () => startGithubLogin()); $('#cancelGithubLogin')?.addEventListener('click', cancelGithubLogin); $('#checkLoginButton')?.addEventListener('click', checkLogin); $('#checkLoginDialogButton')?.addEventListener('click', checkLogin); $('#copyCode')?.addEventListener('click', copyDeviceCode); $('#commentInput')?.addEventListener('input', updateAuthUi); $('#commentInput')?.addEventListener('keydown', event => { if ((event.ctrlKey || event.metaKey) && event.key === 'Enter') submitComment(); }); $('#submitComment')?.addEventListener('click', submitComment); $('#cancelEdit')?.addEventListener('click', cancelEdit); $('#loadMoreComments')?.addEventListener('click', loadMoreComments); $('#refreshComments')?.addEventListener('click', refreshComments); $('#commentSort')?.addEventListener('change', event => { state.commentSort = event.target.value; refreshComments(); }); $('#menuToggle')?.addEventListener('click', () => { const nav = $('#primaryNav'); const button = $('#menuToggle'); const open = nav.classList.toggle('open'); button.classList.toggle('is-open', open); button.setAttribute('aria-expanded', String(open)); }); $$('.nav-link').forEach(link => link.addEventListener('click', () => { $('#primaryNav')?.classList.remove('open'); $('#menuToggle')?.classList.remove('is-open'); $('#menuToggle')?.setAttribute('aria-expanded', 'false'); })); window.addEventListener('scroll', updateHeader, { passive: true }); window.addEventListener('resize', () => { if (window.innerWidth > 860) { $('#primaryNav')?.classList.remove('open'); $('#menuToggle')?.classList.remove('is-open'); $('#menuToggle')?.setAttribute('aria-expanded', 'false'); } }, { passive: true }); document.addEventListener('keydown', event => { if (event.key === 'Escape') { $('#primaryNav')?.classList.remove('open'); $('#menuToggle')?.classList.remove('is-open'); $('#menuToggle')?.setAttribute('aria-expanded', 'false'); const dialog = $('#connectDialog'); if (dialog?.open) closeConnect(); } }); updateHeader(); }
function setupLanguage() { initI18n(lang => { applyLanguage(lang); if (state.issue) renderIssue(); renderComments(); updateAuthUi(); }); }
function finishLoader() { const loader = $('#siteLoader'); if (loader) loader.remove(); }
async function loadAll() { try { const result = await fetchIssue(state.target); state.issue = result.data; renderIssue(); $('#rateLabel').textContent = result.rate?.remaining ?? '—'; const [reactionsResult] = await Promise.all([fetchAllIssueReactions(state.target), loadComments({ reset: true })]); state.reactions = reactionsResult; renderReactions(); renderComments(); await restoreUser(); } catch (error) { console.error(error); showError(tr('unavailable'), error.message || tr('unavailableText')); } }
async function init() { initTheme(); initI18n(); setupEvents(); setupLanguage(); $('#year').textContent = String(new Date().getFullYear()); state.target = parseIssueUrl(new URLSearchParams(location.search).get('post') || ''); if (!state.target) { showError(tr('invalidPost'), tr('unavailableText')); finishLoader(); return; } await loadAll(); await resumePendingLogin(); finishLoader(); applyLanguage(getLanguage()); }
init();
